<?php

namespace AppBundle\Repository;

/**
 * ContractorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractorRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllContractors()
    {
        return $this->createQueryBuilder('con')
            ->where("con.status <> :status OR con.status IS NULL")
            ->setParameter('status', 'D')
            ->getQuery()
            ->getResult();

    }

    public function findOneContractor($id)
    {
        return $this->createQueryBuilder('con')
            ->where('con.id = :contractorId')
            ->andWhere("con.status <> :status OR con.status IS NULL")
            ->setParameters(array('contractorId' => $id, 'status' => 'D'))
            ->getQuery()
            ->getResult();
    }
}
