<?php

namespace AppBundle\Repository;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllInvoices()
    {
        return $this->createQueryBuilder('i')
            ->where("i.status <> :status OR i.status IS NULL")
            ->setParameter('status', 'D')
            ->getQuery()
            ->getResult();

    }

    public function findOneInvoice($id)
    {
        return $this->createQueryBuilder('i')
            ->select(array('i', 'c, pti', 'p'))
            ->where('i.id = :invoiceId')
            ->andWhere("i.status <> :status OR i.status IS NULL")
            ->leftJoin('i.contractor', 'c')
            ->leftJoin('i.productToInvoice', 'pti')
            ->leftJoin('pti.product', 'p')
            ->setParameters(array('invoiceId' => $id, 'status' => 'D'))
            ->getQuery()
            ->getResult();
    }

    public function findLastInvoiceId()
    {
        return $this->createQueryBuilder('i')
            ->select('i.id')
            ->setMaxResults( 1 )
            ->orderBy('i.id', 'DESC')
            ->getQuery()
            ->getSingleResult();
    }
}
