<?php

namespace AppBundle\Repository;

/**
 * ProductToInvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductToInvoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
